# Generated by Django 5.0.2 on 2025-11-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=50, unique=True)),
                ('data_hash', models.CharField(max_length=128)),
                ('model_path', models.CharField(max_length=300)),
                ('last_trained_at', models.DateTimeField(auto_now=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
